### ISSUE TITLE
抓取错题中，错题库不再增加

### ISSUE THREAD

**Issue by Thundor404** [wangzexi/yiban-assistant#2]
反复抓取考试抓取错题时，错题库增长到一定程度就不再增加，是网站有做相关的检测吗😂

**Comment by wangzexi** [comment]
大概是所有题都错过一遍了，没新题了。

**Comment by Thundor404** [comment]
但是实际使用的使用的时候，似乎还是很多题没抓取到，每次只能自动做不到一半的题

**Comment by wangzexi** [comment]
注意一下抓取函数的页数？

https://github.com/wangzexi/yiban-assistant/blob/master/src/index.js#L18

**Comment by Thundor404** [comment]
指的是这个页数？这个页数指的是错题库的页数吗？
https://github.com/wangzexi/yiban-assistant/blob/7b2ff36d953b9f10487789489968036497c5aaae/src/index.js#L36

**Comment by wangzexi** [comment]
是的，这是脚本最多抓取的错题库的页数，如果你的错题有 `5` 页，而脚本只抓了 `3` 页，那确实会抓不全。

这个参数可以设很高，比如 `30` 页，脚本会根据题目 `id` 去重。

**Comment by wangzexi** [comment]
> 每次只能自动做不到一半的题

会提示题库中没有该 `id` 的题是吗？

**Comment by wangzexi** [comment]
事实上我感觉我抓的题库已经很全了，我这边测试都是满分。

会不会是你的操作问题？
https://github.com/wangzexi/yiban-assistant/issues/1#issuecomment-694650443

**Comment by Thundor404** [comment]
> > 每次只能自动做不到一半的题
> 
> 会提示题库中没有该 `id` 的题是吗？

是的，显示没有该id的题，非常神秘

检查了一下db.json和错题库，发现确实只抓了200来个新的题，有些不知道哪来的题



> 事实上我感觉我抓的题库已经很全了，我这边测试都是满分。
> 
> 会不会是你的操作问题？
> [#1 (comment)](https://github.com/wangzexi/yiban-assistant/issues/1#issuecomment-694650443)

- 我把错体页的cookie填进了env
- 然后把index里的name和uri和pageCount改了下。页数设置应该没问题
https://github.com/wangzexi/yiban-assistant/blob/7b2ff36d953b9f10487789489968036497c5aaae/src/index.js#L24-L26

改动的部分

```
async function crawl () {
  const cookies = process.env.COOKIES

  // 从我的错题里抓取题目
  const courses = [
   /**{
      name: '本科生学籍管理规定',
      uri: 'http://www.yiban.cn/t/student/showmisinfo/name/%E6%9C%AC%E7%A7%91%E7%94%9F%E5%AD%A6%E7%B1%8D%E7%AE%A1%E7%90%86%E8%A7%84%E5%AE%9A/courseid/471/page/',
      pageCount: 2 // 抓取页数
    },
    {
      name: '纪律与处分规定',
      uri: 'http://www.yiban.cn/t/student/showmisinfo/name/%E7%BA%AA%E5%BE%8B%E4%B8%8E%E5%A4%84%E5%88%86%E8%A7%84%E5%AE%9A/courseid/470/page/',
      pageCount: 3
    },
    {
      name: '安全教育',
      uri: 'http://www.yiban.cn/t/student/showmisinfo/name/%E5%AE%89%E5%85%A8%E6%95%99%E8%82%B2/courseid/428/page/',
      pageCount: 3
    },**/
    {
      name: '2020级博士研究生入学教育',
      uri: 'http://www.yiban.cn/t/student/showmisinfo/name/2020%E7%BA%A7%E5%8D%9A%E5%A3%AB%E7%A0%94%E7%A9%B6%E7%94%9F%E5%85%A5%E5%AD%A6%E6%95%99%E8%82%B2/courseid/15756/page',
      pageCount: 5
    }
  ]

  for (const course of courses) {
    for (let i = 1; i < course.pageCount + 1; ++i) {
      const questions = await getQstByPage(cookies, course.uri + i)
      db.get('questions').push(...questions).write()
      console.log(course.name, '页数', i, questions.length)
    }
  }
  // 去重
  db.set('questions', db.get('questions').uniqBy('id').value()).write()

  console.log('完成', db.get('questions').value().length)
}
```

**Comment by wangzexi** [comment]
应该是 `uri` 需要以 `/` 结尾。

**Comment by Thundor404** [comment]
> 应该是 `uri` 需要以 `/` 结尾。

确实是，更改了之后可以正常抓取到全部题目👏

**Comment by wangzexi** [comment]
有兴趣欢迎 PR 一下你的题库。😋
